[metadata]
name = mace-torch
version = attr: mace.__version__
short_description = MACE - Fast and accurate machine learning interatomic potentials with higher order equivariant message passing.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/ACEsuit/mace
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent
    License :: OSI Approved :: MIT License

[options]
packages = find:
python_requires = >=3.7
install_requires =
    # torch>=1.12
    # e3nn==0.4.4
    # numpy
    # opt_einsum
    # ase
    # torch-ema
    # prettytable
    # matscipy
    # h5py
    # torchmetrics
    # python-hostlist
    # configargparse
    # GitPython
    # pyYAML
    # tqdm
    # lmdb==1.7.5
    # orjson
    # # for plotting:
    # matplotlib
    # pandas
    ase==3.23.0
    astroid==3.2.4
    black==24.8.0
    cfgv==3.4.0
    click==8.1.8
    ConfigArgParse==1.7.1
    contourpy==1.1.1
    cycler==0.12.1
    dill==0.4.0
    distlib==0.4.0
    e3nn==0.4.4
    exceptiongroup==1.3.1
    execnet==2.1.2
    filelock==3.16.1
    fonttools==4.57.0
    fsspec==2025.3.0
    gitdb==4.0.12
    GitPython==3.1.46
    h5py==3.11.0
    identify==2.6.1
    importlib_resources==6.4.5
    iniconfig==2.1.0
    isort==5.13.2
    Jinja2==3.1.6
    kiwisolver==1.4.7
    lightning-utilities==0.11.9
    lmdb==1.7.5
    mace-torch @ file:///home/runner/work/mace/mace
    MarkupSafe==2.1.5
    matplotlib==3.7.5
    matscipy==1.1.1
    mccabe==0.7.0
    mpmath==1.3.0
    mypy==1.14.1
    mypy_extensions==1.1.0
    networkx==3.1
    nodeenv==1.10.0
    numpy==1.24.4
    nvidia-cublas-cu12==12.1.3.1
    nvidia-cuda-cupti-cu12==12.1.105
    nvidia-cuda-nvrtc-cu12==12.1.105
    nvidia-cuda-runtime-cu12==12.1.105
    nvidia-cudnn-cu12==9.1.0.70
    nvidia-cufft-cu12==11.0.2.54
    nvidia-curand-cu12==10.3.2.106
    nvidia-cusolver-cu12==11.4.5.107
    nvidia-cusparse-cu12==12.1.0.106
    nvidia-nccl-cu12==2.20.5
    nvidia-nvjitlink-cu12==12.9.86
    nvidia-nvtx-cu12==12.1.105
    opt-einsum-fx==0.1.4
    opt_einsum==3.4.0
    orjson==3.10.15
    packaging==26.0
    pandas==2.0.3
    pathspec==0.12.1
    pillow==10.4.0
    platformdirs==4.3.6
    pluggy==1.5.0
    pre-commit==3.5.0
    prettytable==3.11.0
    py-cpuinfo==9.0.0
    pylint==3.2.7
    pyparsing==3.1.4
    pytest==8.3.5
    pytest-benchmark==4.0.0
    pytest-split==0.10.0
    pytest-xdist==3.6.1
    python-dateutil==2.9.0.post0
    python_hostlist==2.3.0
    pytz==2025.2
    PyYAML==6.0.3
    scipy==1.10.1
    six==1.17.0
    smmap==5.0.2
    sympy==1.13.3
    tomli==2.4.0
    tomlkit==0.13.3
    torch==2.4.1
    torch-ema==0.3
    torchmetrics==1.5.2
    tqdm==4.67.3
    triton==3.0.0
    typing_extensions==4.13.2
    tzdata==2025.3
    virtualenv==20.36.1
    wcwidth==0.6.0
    zipp==3.20.2

[options.entry_points]
console_scripts =
    mace_active_learning_md  =  mace.cli.active_learning_md:main
    mace_create_lammps_model  =  mace.cli.create_lammps_model:main
    mace_eval_configs  =  mace.cli.eval_configs:main
    mace_plot_train  =  mace.cli.plot_train:main
    mace_run_train  =  mace.cli.run_train:main
    mace_prepare_data  =  mace.cli.preprocess_data:main
    mace_finetuning_select = mace.cli.fine_tuning_select:main
    mace_convert_device  =  mace.cli.convert_device:main
    mace_select_head =  mace.cli.select_head:main
    mace_e3nn_cueq = mace.cli.convert_e3nn_cueq:main
    mace_cueq_to_e3nn = mace.cli.convert_cueq_e3nn:main

[options.extras_require]
wandb = wandb
fpsample = fpsample
dev =
    black
    isort
    mypy
    pre-commit
    pytest
    pytest-benchmark
    pylint
schedulefree = schedulefree
cueq = cuequivariance-torch>=0.2.0
cueq-cuda-11 = cuequivariance-ops-torch-cu11>=0.2.0
cueq-cuda-12 = cuequivariance-ops-torch-cu12>=0.2.0
