name: Pre-Commit Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install requirements
        run: |
          set -xe  # show each command and stop on errors
          pip install -U pip setuptools wheel
          pip install pylint black wandb tqdm
          pip install .[dev]

      - name: Run black (verbose)
        run: |
          set -xe
          python -m black --verbose .

      - name: Run pre-commit (verbose)
        uses: pre-commit/action@v3.0.0
        env:
          PRE_COMMIT_COLOR: always
          PRE_COMMIT_HOME: ~/.cache/pre-commit
        with:
          extra_args: --verbose --all-files
